@echo off
chcp 65001 >nul 2>&1
setlocal EnableDelayedExpansion

:: Colors
set "RED=[91m"
set "GREEN=[92m"
set "YELLOW=[93m"
set "BLUE=[94m"
set "CYAN=[96m"
set "WHITE=[97m"
set "RESET=[0m"

echo %BLUE%⚙️  Configurando arquivo .env...%RESET%

:: Backup existing .env if it exists
if exist ".env" (
    echo %YELLOW%📋 Fazendo backup do .env existente...%RESET%
    copy ".env" ".env.backup.%date:~-4%%date:~3,2%%date:~0,2%" >nul
)

:: Create new .env file
> ".env" (
echo # FastFood API - Environment Configuration
echo # Generated by FastFood Initializer
echo # Date: %date% %time%
echo.
echo # Database Configuration
echo DB_PASSWORD=FastFood2024
echo.
echo # Application Configuration  
echo ASPNETCORE_ENVIRONMENT=Development
echo.
echo # SSL/TLS Certificate Configuration
echo CERT_PASSWORD=fastfood123
echo.
echo # SQL Server Configuration
echo MSSQL_PID=Express
echo.
echo # Timezone
echo TZ=America/Sao_Paulo
)

echo %GREEN%✅ Arquivo .env configurado com sucesso%RESET%
echo %WHITE%📄 Localização: %cd%\.env%RESET%

:: Show configured values
echo %CYAN%📋 Configurações aplicadas:%RESET%
echo %WHITE%   Database Password: FastFood2024%RESET%
echo %WHITE%   Certificate Password: fastfood123%RESET%
echo %WHITE%   Environment: Development%RESET%
echo %WHITE%   SQL Server Edition: Express%RESET%

exit /b 0
