version: '3.8'

# Configuração para desenvolvimento
# Suporta tanto HTTP quanto HTTPS para flexibilidade no desenvolvimento

services:
  # Init container para migrations
  migrations:
    build:
      context: .
      dockerfile: Dockerfile.migrations
    environment:
      - ConnectionStrings__DefaultConnection=Server=db;Database=FastFoodDb;User Id=sa;Password=${DB_PASSWORD};TrustServerCertificate=true;MultipleActiveResultSets=true
    networks:
      - fastfood-network
    depends_on:
      db:
        condition: service_healthy
    restart: "no"

  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:8080"   # HTTP para desenvolvimento e testes
      - "5001:8443"   # HTTPS (recomendado)
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:8443;http://+:8080
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/app/certs/fastfood-dev.pfx
      - ASPNETCORE_Kestrel__Certificates__Default__Password=${CERT_PASSWORD:-fastfood123}
      - ConnectionStrings__DefaultConnection=Server=db;Database=FastFoodDb;User Id=sa;Password=${DB_PASSWORD};TrustServerCertificate=true;MultipleActiveResultSets=true
      - TZ=${TZ:-America/Sao_Paulo}
    volumes:
      - ./certs:/app/certs:ro
    networks:
      - fastfood-network
    depends_on:
      db:
        condition: service_healthy
      migrations:
        condition: service_completed_successfully
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "-k", "https://localhost:8443/health", "||", "curl", "-f", "http://localhost:8080/health", "||", "exit", "1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=${DB_PASSWORD}
      - MSSQL_PID=${MSSQL_PID:-Express}
      - TZ=${TZ:-America/Sao_Paulo}
    ports:
      - "1433:1433"
    volumes:
      - fastfood-data:/var/opt/mssql
    networks:
      - fastfood-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P ${DB_PASSWORD} -Q 'SELECT 1' || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

volumes:
  fastfood-data:
    name: fastfood-data

networks:
  fastfood-network:
    name: fastfood-network
    driver: bridge
