version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:80"
      - "5001:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80;https://+:443
      - ConnectionStrings__DefaultConnection=Server=db;Database=FastFoodDb;User Id=sa;Password=${DB_PASSWORD};TrustServerCertificate=true
      - TZ=America/Sao_Paulo
    networks:
      - fastfood-network
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=${DB_PASSWORD}
      - MSSQL_PID=Express
      - TZ=America/Sao_Paulo
    ports:
      - "1433:1433"
    volumes:
      - fastfood-data:/var/opt/mssql
    networks:
      - fastfood-network
    restart: unless-stopped

volumes:
  fastfood-data:
    name: fastfood-data

networks:
  fastfood-network:
    name: fastfood-network
    driver: bridge
