apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: arn:aws:iam::939111385333:role/fastfood-lambda-github-role
      username: github-actions
      groups:
        - system:masters
