apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastfood-api
  labels:
    app: fastfood
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fastfood
  template:
    metadata:
      labels:
        app: fastfood
    spec:
      containers:
        - name: fastfood-api
          image: 939111385333.dkr.ecr.sa-east-1.amazonaws.com/fastfood-api:latest
          ports:
            - containerPort: 8080
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Production"
            - name: ConnectionStrings__DefaultConnection
              valueFrom:
                secretKeyRef:
                  name: fastfood-secrets
                  key: db-connection
            - name: Jwt__Secret
              valueFrom:
                secretKeyRef:
                  name: fastfood-secrets
                  key: jwt-secret
            - name: Jwt__Issuer
              value: "fastfood-api"
            - name: Jwt__Audience
              value: "fastfood-clients"
            - name: MercadoPago__AccessToken
              valueFrom:
                secretKeyRef:
                  name: fastfood-secrets
                  key: mp-access-token
            - name: MercadoPago__PublicKey
              valueFrom:
                secretKeyRef:
                  name: fastfood-secrets
                  key: mp-public-key
            - name: UseFakePayment
              value: "true"
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 30
